name: Caladins
favicon: null
layout_spectrum: 0.50016
typography_spectrum: 0.71715
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ff811c'
    - '#f29a36'
    - '#feebc2'
    - '#f4a580'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
