typography_spectrum: 0.9789171047963312
color:
  brandColors:
    - '#E6E2AF'
    - '#A7A37E'
    - '#EFECCA'
    - '#046380'
    - '#002F2F'
  brandStrength: 0.42115031287728777
  lightness: 0.8474430923692254
  saturation: 0.08541735393695976
  rhythmicContrast: 0.12571813743727484
github: true
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.5974991458395292
analytics:
  google: null
  facebook: null
  twitter: '1963'
author:
  name: John B Stone
  email: jstone63@hotmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/8b5ea9e6-b302-4ba5-9951-5d5ae2139035.png
name: Caladins
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Real Estate
    id: df083ab6-0bda-4db9-a532-97df4df7941f
    type: content
  - name: Computers
    id: e55895f5-26ec-446d-a0a1-51f3f7497540
    type: content
  - name: Books
    id: b2ea8bfd-08ea-4a5b-8741-4dcbba50a674
    type: content
  - name: About Caladins
    id: 715b6c63-8eff-4bb5-a25e-f255ff037b70
    type: content
favicon: null
title: Caladins
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/46218dd7-696a-4992-a319-6446f9c124ed.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/46218dd7-696a-4992-a319-6446f9c124ed.png
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: 'Information on the Caladin ITS, LLC businesses'
purpose: []
