typography_spectrum: 0.6972870695304199
color:
  brandColors:
    - '#FFFFFF'
    - '#FF7F27'
    - '#FF974F'
    - '#FFBF93'
    - '#650249'
  brandStrength: 0.12883422817546172
  lightness: 0.1537363213164234
  saturation: 0.9306739929097124
  rhythmicContrast: 0.5532628558087394
github: true
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.5943825057224545
analytics:
  google: null
  facebook: null
  twitter: '1963'
author:
  name: John B Stone
  email: jstone63@hotmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/3d023892-83c2-4579-ba4a-e1b9c2862620.png
name: Caladins
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Data
    id: e55895f5-26ec-446d-a0a1-51f3f7497540
    type: content
  - name: Property
    id: df083ab6-0bda-4db9-a532-97df4df7941f
    type: content
  - name: Books
    id: b2ea8bfd-08ea-4a5b-8741-4dcbba50a674
    type: content
  - name: About
    id: 715b6c63-8eff-4bb5-a25e-f255ff037b70
    type: content
favicon: null
title: CALADIN
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/5c4c9290-5451-46f0-9662-662806cad691.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/5c4c9290-5451-46f0-9662-662806cad691.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: 'Information on the Caladin ITS, LLC businesses'
purpose:
  - type: contact
    url: 'tel:5412281302'
    label: Click to Call
  - type: contact
    url: 'tel:5412281302'
    label: '5412281302'
